// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLiteEFCore.Data;

#nullable disable

namespace SQLiteEFCore.Migrations
{
    [DbContext(typeof(EmployeeDataContext))]
    [Migration("20230320210327_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("SQLiteEFCore.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "93.247.225.92",
                            Department = "Female",
                            Email = "bchurms0@usda.gov",
                            FirstName = "Billie",
                            LastName = "Churms"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "186.163.30.9",
                            Department = "Female",
                            Email = "cbunney1@craigslist.org",
                            FirstName = "Clem",
                            LastName = "Bunney"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "86.236.123.19",
                            Department = "Male",
                            Email = "twilcinskis2@clickbank.net",
                            FirstName = "Tab",
                            LastName = "Wilcinskis"
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "163.137.92.211",
                            Department = "Female",
                            Email = "fthrussell3@slate.com",
                            FirstName = "Freda",
                            LastName = "Thrussell"
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "200.178.41.254",
                            Department = "Female",
                            Email = "mkendall4@theguardian.com",
                            FirstName = "Marlie",
                            LastName = "Kendall"
                        },
                        new
                        {
                            Id = 6,
                            Avatar = "188.80.18.29",
                            Department = "Female",
                            Email = "ecotman5@dropbox.com",
                            FirstName = "Em",
                            LastName = "Cotman"
                        },
                        new
                        {
                            Id = 7,
                            Avatar = "185.47.190.64",
                            Department = "Male",
                            Email = "tsissland6@adobe.com",
                            FirstName = "Taddeo",
                            LastName = "Sissland"
                        },
                        new
                        {
                            Id = 8,
                            Avatar = "181.50.83.142",
                            Department = "Male",
                            Email = "sjanczyk7@twitpic.com",
                            FirstName = "Stirling",
                            LastName = "Janczyk"
                        },
                        new
                        {
                            Id = 9,
                            Avatar = "212.106.228.161",
                            Department = "Male",
                            Email = "dbertin8@nasa.gov",
                            FirstName = "Dukey",
                            LastName = "Bertin"
                        },
                        new
                        {
                            Id = 10,
                            Avatar = "229.51.110.20",
                            Department = "Female",
                            Email = "atoll9@pcworld.com",
                            FirstName = "Ardelis",
                            LastName = "Toll"
                        },
                        new
                        {
                            Id = 11,
                            Avatar = "233.38.178.55",
                            Department = "Female",
                            Email = "emccronea@buzzfeed.com",
                            FirstName = "Emlyn",
                            LastName = "McCrone"
                        },
                        new
                        {
                            Id = 12,
                            Avatar = "84.120.103.48",
                            Department = "Female",
                            Email = "aderechterb@networksolutions.com",
                            FirstName = "Agneta",
                            LastName = "De Rechter"
                        },
                        new
                        {
                            Id = 13,
                            Avatar = "59.199.251.206",
                            Department = "Female",
                            Email = "mvreedec@behance.net",
                            FirstName = "Maegan",
                            LastName = "Vreede"
                        },
                        new
                        {
                            Id = 14,
                            Avatar = "115.136.4.239",
                            Department = "Male",
                            Email = "aparsonsond@loc.gov",
                            FirstName = "Archer",
                            LastName = "Parsonson"
                        },
                        new
                        {
                            Id = 15,
                            Avatar = "74.41.63.69",
                            Department = "Female",
                            Email = "ssuttiee@mayoclinic.com",
                            FirstName = "Sheila",
                            LastName = "Suttie"
                        },
                        new
                        {
                            Id = 16,
                            Avatar = "162.11.43.7",
                            Department = "Male",
                            Email = "jfiddianf@list-manage.com",
                            FirstName = "Jeremiah",
                            LastName = "Fiddian"
                        },
                        new
                        {
                            Id = 17,
                            Avatar = "182.84.110.5",
                            Department = "Female",
                            Email = "jlameyg@princeton.edu",
                            FirstName = "Juliann",
                            LastName = "Lamey"
                        },
                        new
                        {
                            Id = 18,
                            Avatar = "5.96.235.206",
                            Department = "Male",
                            Email = "kcarush@washingtonpost.com",
                            FirstName = "Kippie",
                            LastName = "Carus"
                        },
                        new
                        {
                            Id = 19,
                            Avatar = "78.5.19.223",
                            Department = "Male",
                            Email = "gsmalecombei@reference.com",
                            FirstName = "Gary",
                            LastName = "Smalecombe"
                        },
                        new
                        {
                            Id = 20,
                            Avatar = "63.63.154.175",
                            Department = "Male",
                            Email = "syeellj@dailymail.co.uk",
                            FirstName = "Stillmann",
                            LastName = "Yeell"
                        },
                        new
                        {
                            Id = 21,
                            Avatar = "191.93.135.211",
                            Department = "Female",
                            Email = "dmauricek@unesco.org",
                            FirstName = "Dareen",
                            LastName = "Maurice"
                        },
                        new
                        {
                            Id = 22,
                            Avatar = "154.205.73.155",
                            Department = "Male",
                            Email = "bsuarezl@cnn.com",
                            FirstName = "Bevin",
                            LastName = "Suarez"
                        },
                        new
                        {
                            Id = 23,
                            Avatar = "237.192.48.140",
                            Department = "Female",
                            Email = "clarmetm@rambler.ru",
                            FirstName = "Cynthea",
                            LastName = "Larmet"
                        },
                        new
                        {
                            Id = 24,
                            Avatar = "39.176.104.252",
                            Department = "Female",
                            Email = "anorburyn@twitpic.com",
                            FirstName = "Ardra",
                            LastName = "Norbury"
                        },
                        new
                        {
                            Id = 25,
                            Avatar = "141.142.33.54",
                            Department = "Female",
                            Email = "amcdonello@yale.edu",
                            FirstName = "Agatha",
                            LastName = "McDonell"
                        },
                        new
                        {
                            Id = 26,
                            Avatar = "39.115.64.68",
                            Department = "Female",
                            Email = "omanvellep@wikimedia.org",
                            FirstName = "Orella",
                            LastName = "Manvelle"
                        },
                        new
                        {
                            Id = 27,
                            Avatar = "47.129.75.150",
                            Department = "Male",
                            Email = "ghassinq@abc.net.au",
                            FirstName = "Gunar",
                            LastName = "Hassin"
                        },
                        new
                        {
                            Id = 28,
                            Avatar = "60.54.104.17",
                            Department = "Male",
                            Email = "ssutterr@goo.ne.jp",
                            FirstName = "Silvain",
                            LastName = "Sutter"
                        },
                        new
                        {
                            Id = 29,
                            Avatar = "21.148.104.113",
                            Department = "Bigender",
                            Email = "ocabraras@mozilla.org",
                            FirstName = "Odetta",
                            LastName = "Cabrara"
                        },
                        new
                        {
                            Id = 30,
                            Avatar = "239.248.93.89",
                            Department = "Female",
                            Email = "fdencst@instagram.com",
                            FirstName = "Flora",
                            LastName = "Dencs"
                        },
                        new
                        {
                            Id = 31,
                            Avatar = "172.153.148.42",
                            Department = "Female",
                            Email = "pmillichipu@spotify.com",
                            FirstName = "Petronille",
                            LastName = "Millichip"
                        },
                        new
                        {
                            Id = 32,
                            Avatar = "66.23.131.133",
                            Department = "Male",
                            Email = "gjaffrayv@cloudflare.com",
                            FirstName = "Georgi",
                            LastName = "Jaffray"
                        },
                        new
                        {
                            Id = 33,
                            Avatar = "206.252.80.75",
                            Department = "Male",
                            Email = "bpollokw@github.io",
                            FirstName = "Berny",
                            LastName = "Pollok"
                        },
                        new
                        {
                            Id = 34,
                            Avatar = "68.202.94.210",
                            Department = "Non-binary",
                            Email = "hhumesx@nifty.com",
                            FirstName = "Hernando",
                            LastName = "Humes"
                        },
                        new
                        {
                            Id = 35,
                            Avatar = "56.230.85.149",
                            Department = "Female",
                            Email = "abowketty@rakuten.co.jp",
                            FirstName = "Aurea",
                            LastName = "Bowkett"
                        },
                        new
                        {
                            Id = 36,
                            Avatar = "253.53.63.121",
                            Department = "Female",
                            Email = "ldowseyz@1688.com",
                            FirstName = "Lavina",
                            LastName = "Dowsey"
                        },
                        new
                        {
                            Id = 37,
                            Avatar = "157.171.72.126",
                            Department = "Male",
                            Email = "eralph10@rakuten.co.jp",
                            FirstName = "Elnar",
                            LastName = "Ralph"
                        },
                        new
                        {
                            Id = 38,
                            Avatar = "110.152.135.226",
                            Department = "Female",
                            Email = "dhallyburton11@imdb.com",
                            FirstName = "Dorena",
                            LastName = "Hallyburton"
                        },
                        new
                        {
                            Id = 39,
                            Avatar = "241.42.234.92",
                            Department = "Female",
                            Email = "mcostigan12@about.com",
                            FirstName = "Myrle",
                            LastName = "Costigan"
                        },
                        new
                        {
                            Id = 40,
                            Avatar = "71.29.222.161",
                            Department = "Female",
                            Email = "drasor13@ameblo.jp",
                            FirstName = "Dorette",
                            LastName = "Rasor"
                        },
                        new
                        {
                            Id = 41,
                            Avatar = "157.185.84.29",
                            Department = "Male",
                            Email = "modger14@prlog.org",
                            FirstName = "Maximilien",
                            LastName = "Odger"
                        },
                        new
                        {
                            Id = 42,
                            Avatar = "224.54.20.162",
                            Department = "Male",
                            Email = "itilne15@prlog.org",
                            FirstName = "Ingram",
                            LastName = "Tilne"
                        },
                        new
                        {
                            Id = 43,
                            Avatar = "52.31.32.90",
                            Department = "Female",
                            Email = "cbeadnell16@about.com",
                            FirstName = "Cthrine",
                            LastName = "Beadnell"
                        },
                        new
                        {
                            Id = 44,
                            Avatar = "99.22.146.3",
                            Department = "Male",
                            Email = "epleass17@columbia.edu",
                            FirstName = "Eadmund",
                            LastName = "Pleass"
                        },
                        new
                        {
                            Id = 45,
                            Avatar = "181.6.157.35",
                            Department = "Female",
                            Email = "jdelavaletteparisot18@latimes.com",
                            FirstName = "Jacintha",
                            LastName = "de la Valette Parisot"
                        },
                        new
                        {
                            Id = 46,
                            Avatar = "228.205.3.31",
                            Department = "Female",
                            Email = "knowak19@phoca.cz",
                            FirstName = "Kore",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 47,
                            Avatar = "88.111.54.173",
                            Department = "Male",
                            Email = "dnoulton1a@ucla.edu",
                            FirstName = "Doyle",
                            LastName = "Noulton"
                        },
                        new
                        {
                            Id = 48,
                            Avatar = "38.248.72.153",
                            Department = "Female",
                            Email = "matkirk1b@wufoo.com",
                            FirstName = "Madelene",
                            LastName = "Atkirk"
                        },
                        new
                        {
                            Id = 49,
                            Avatar = "196.14.231.174",
                            Department = "Bigender",
                            Email = "cbreeder1c@si.edu",
                            FirstName = "Carolyne",
                            LastName = "Breeder"
                        },
                        new
                        {
                            Id = 50,
                            Avatar = "24.165.109.241",
                            Department = "Male",
                            Email = "clivock1d@mapy.cz",
                            FirstName = "Calv",
                            LastName = "Livock"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
